#!/bin/bash
MAINVERSION=$(cat <<'BABEL_TABLE'
0
BABEL_TABLE
)
SVNVERSION=$(cat <<'BABEL_TABLE'
9
BABEL_TABLE
)
VER=$(cat <<'BABEL_TABLE'

BABEL_TABLE
)
STATE=$(cat <<'BABEL_TABLE'
unregistered
BABEL_TABLE
)
sed -i s/MAINVERSION/$MAINVERSION/ ./pkg/DESCRIPTION
sed -i s/SVNVERSION/$SVNVERSION/ ./pkg/DESCRIPTION
